# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/cwang/Courses/ECE350/final_project/ECE350_Dino/dino_proj/dino_proj.runs/synth_1/Wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 1
set_param synth.incrementalSynthesisCache C:/Users/cwang/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-28692-CathComp/incrSyn
set_param xicom.use_bs_reader 1
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/cwang/Courses/ECE350/final_project/ECE350_Dino/dino_proj/dino_proj.cache/wt [current_project]
set_property parent.project_path C:/Users/cwang/Courses/ECE350/final_project/ECE350_Dino/dino_proj/dino_proj.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/cwang/Courses/ECE350/final_project/ECE350_Dino/dino_proj/dino_proj.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_mem {
  C:/Users/cwang/Courses/ECE350/final_project/ECE350_Dino/processor/problem_lwfastbranch.mem
  C:/Users/cwang/Courses/ECE350/final_project/ECE350_Dino/processor/init_mem.mem
  C:/Users/cwang/Courses/ECE350/final_project/ECE350_Dino/assets/dino.mem
  C:/Users/cwang/Courses/ECE350/final_project/ECE350_Dino/assets/background.mem
}
read_verilog -library xil_defaultlib {
  C:/Users/cwang/Courses/ECE350/final_project/ECE350_Dino/RAM.v
  C:/Users/cwang/Courses/ECE350/final_project/ECE350_Dino/ROM.v
  C:/Users/cwang/Courses/ECE350/final_project/ECE350_Dino/VGAController.v
  C:/Users/cwang/Courses/ECE350/final_project/ECE350_Dino/VGATimingGenerator.v
  C:/Users/cwang/Courses/ECE350/final_project/ECE350_Dino/processor/alu.v
  C:/Users/cwang/Courses/ECE350/final_project/ECE350_Dino/processor/and32.v
  C:/Users/cwang/Courses/ECE350/final_project/ECE350_Dino/processor/booth_ctrl.v
  C:/Users/cwang/Courses/ECE350/final_project/ECE350_Dino/processor/bypass.v
  C:/Users/cwang/Courses/ECE350/final_project/ECE350_Dino/processor/cla_32bit.v
  C:/Users/cwang/Courses/ECE350/final_project/ECE350_Dino/processor/cla_8bit.v
  C:/Users/cwang/Courses/ECE350/final_project/ECE350_Dino/processor/counter.v
  C:/Users/cwang/Courses/ECE350/final_project/ECE350_Dino/processor/decoder32.v
  C:/Users/cwang/Courses/ECE350/final_project/ECE350_Dino/processor/dffe_ref.v
  C:/Users/cwang/Courses/ECE350/final_project/ECE350_Dino/processor/div.v
  C:/Users/cwang/Courses/ECE350/final_project/ECE350_Dino/processor/divcounter.v
  C:/Users/cwang/Courses/ECE350/final_project/ECE350_Dino/processor/dx_latch.v
  C:/Users/cwang/Courses/ECE350/final_project/ECE350_Dino/processor/fastbranch_bypass.v
  C:/Users/cwang/Courses/ECE350/final_project/ECE350_Dino/processor/fd_latch.v
  C:/Users/cwang/Courses/ECE350/final_project/ECE350_Dino/processor/m_latch.v
  C:/Users/cwang/Courses/ECE350/final_project/ECE350_Dino/processor/mul.v
  C:/Users/cwang/Courses/ECE350/final_project/ECE350_Dino/processor/multdiv.v
  C:/Users/cwang/Courses/ECE350/final_project/ECE350_Dino/processor/mux_2.v
  C:/Users/cwang/Courses/ECE350/final_project/ECE350_Dino/processor/mux_3.v
  C:/Users/cwang/Courses/ECE350/final_project/ECE350_Dino/processor/mux_4.v
  C:/Users/cwang/Courses/ECE350/final_project/ECE350_Dino/processor/mux_8.v
  C:/Users/cwang/Courses/ECE350/final_project/ECE350_Dino/processor/my_tri.v
  C:/Users/cwang/Courses/ECE350/final_project/ECE350_Dino/processor/not32.v
  C:/Users/cwang/Courses/ECE350/final_project/ECE350_Dino/processor/or32.v
  C:/Users/cwang/Courses/ECE350/final_project/ECE350_Dino/processor.v
  C:/Users/cwang/Courses/ECE350/final_project/ECE350_Dino/processor/pw_latch.v
  C:/Users/cwang/Courses/ECE350/final_project/ECE350_Dino/processor/regfile.v
  C:/Users/cwang/Courses/ECE350/final_project/ECE350_Dino/processor/register.v
  C:/Users/cwang/Courses/ECE350/final_project/ECE350_Dino/processor/register5.v
  C:/Users/cwang/Courses/ECE350/final_project/ECE350_Dino/processor/register64.v
  C:/Users/cwang/Courses/ECE350/final_project/ECE350_Dino/processor/register65.v
  C:/Users/cwang/Courses/ECE350/final_project/ECE350_Dino/processor/set_xm_inputs.v
  C:/Users/cwang/Courses/ECE350/final_project/ECE350_Dino/processor/shift_left.v
  C:/Users/cwang/Courses/ECE350/final_project/ECE350_Dino/processor/shift_left1.v
  C:/Users/cwang/Courses/ECE350/final_project/ECE350_Dino/processor/shift_left16.v
  C:/Users/cwang/Courses/ECE350/final_project/ECE350_Dino/processor/shift_left2.v
  C:/Users/cwang/Courses/ECE350/final_project/ECE350_Dino/processor/shift_left4.v
  C:/Users/cwang/Courses/ECE350/final_project/ECE350_Dino/processor/shift_left8.v
  C:/Users/cwang/Courses/ECE350/final_project/ECE350_Dino/processor/shouldReadRD.v
  C:/Users/cwang/Courses/ECE350/final_project/ECE350_Dino/processor/shouldStall.v
  C:/Users/cwang/Courses/ECE350/final_project/ECE350_Dino/processor/sra.v
  C:/Users/cwang/Courses/ECE350/final_project/ECE350_Dino/processor/sra1.v
  C:/Users/cwang/Courses/ECE350/final_project/ECE350_Dino/processor/sra16.v
  C:/Users/cwang/Courses/ECE350/final_project/ECE350_Dino/processor/sra2.v
  C:/Users/cwang/Courses/ECE350/final_project/ECE350_Dino/processor/sra4.v
  C:/Users/cwang/Courses/ECE350/final_project/ECE350_Dino/processor/sra8.v
  C:/Users/cwang/Courses/ECE350/final_project/ECE350_Dino/processor/sx.v
  C:/Users/cwang/Courses/ECE350/final_project/ECE350_Dino/processor/sx_T.v
  C:/Users/cwang/Courses/ECE350/final_project/ECE350_Dino/processor/twos_complement.v
  C:/Users/cwang/Courses/ECE350/final_project/ECE350_Dino/Wrapper.v
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/cwang/Courses/ECE350/final_project/ECE350_Dino/dino_proj/constraints.xdc
set_property used_in_implementation false [get_files C:/Users/cwang/Courses/ECE350/final_project/ECE350_Dino/dino_proj/constraints.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top Wrapper -part xc7a100tcsg324-1
OPTRACE "synth_design" END { }


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Wrapper_utilization_synth.rpt -pb Wrapper_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
